// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'ja-JP'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const jaJPObjects: NonNullable<TranslationData['objects']> = {
  sys_role: {
    label: "ロール",
    pluralLabel: "ロール",
    description: "RBAC アクセス制御のためのロール定義",
    fields: {
      label: {
        label: "表示名"
      },
      name: {
        label: "API 名",
        help: "ロールの一意の機械名（例: admin、editor、viewer）"
      },
      description: {
        label: "説明"
      },
      permissions: {
        label: "権限",
        help: "権限文字列の JSON シリアライズ配列"
      },
      active: {
        label: "有効"
      },
      is_default: {
        label: "デフォルトロール",
        help: "新規ユーザーに自動的に割り当てられます"
      },
      id: {
        label: "ロール ID"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      }
    },
    _views: {
      active: {
        label: "有効"
      },
      default_roles: {
        label: "デフォルト"
      },
      custom: {
        label: "カスタム"
      },
      all_roles: {
        label: "すべて"
      }
    },
    _actions: {
      activate_role: {
        label: "ロールを有効化",
        successMessage: "ロールが有効化されました"
      },
      deactivate_role: {
        label: "ロールを無効化",
        confirmText: "このロールを無効化しますか？このロールを持つユーザーの割り当ては維持されますが、再度有効化するまで権限の付与は停止されます。",
        successMessage: "ロールが無効化されました"
      },
      set_default_role: {
        label: "デフォルトに設定",
        confirmText: "このロールを新規ユーザーのデフォルトロールにしますか？既存のユーザーには影響しません。",
        successMessage: "デフォルトロールを更新しました"
      },
      clone_role: {
        label: "ロールを複製",
        successMessage: "ロールを複製しました"
      }
    }
  },
  sys_permission_set: {
    label: "権限セット",
    pluralLabel: "権限セット",
    description: "細かいアクセス制御のための権限グループ",
    fields: {
      label: {
        label: "表示名"
      },
      name: {
        label: "API 名",
        help: "権限セットの一意の機械名"
      },
      description: {
        label: "説明"
      },
      object_permissions: {
        label: "オブジェクト権限",
        help: "JSON シリアライズされたオブジェクトレベルの CRUD 権限"
      },
      field_permissions: {
        label: "フィールド権限",
        help: "JSON シリアライズされたフィールドレベルの読み取り/書き込み権限"
      },
      system_permissions: {
        label: "システム権限",
        help: "システムケーパビリティ名のJSONシリアライズ配列（例: [\"setup.access\",\"studio.access\",\"manage_users\"]）"
      },
      row_level_security: {
        label: "行レベルセキュリティ",
        help: "行レベルセキュリティポリシーのJSONシリアライズ配列（USING/CHECK 句）"
      },
      tab_permissions: {
        label: "タブ権限",
        help: "アプリのタブ表示のJSONシリアライズマップ（visible | hidden | default_on | default_off）"
      },
      active: {
        label: "有効"
      },
      id: {
        label: "権限セット ID"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      }
    },
    _views: {
      active: {
        label: "有効"
      },
      inactive: {
        label: "無効"
      },
      all_permsets: {
        label: "すべて"
      }
    },
    _actions: {
      activate_permission_set: {
        label: "有効化",
        successMessage: "権限セットが有効化されました"
      },
      deactivate_permission_set: {
        label: "無効化",
        confirmText: "この権限セットを無効化しますか？既存の割り当ては維持されますが、再度有効化するまでアクセスの付与は停止されます。",
        successMessage: "権限セットが無効化されました"
      },
      clone_permission_set: {
        label: "複製",
        successMessage: "権限セットを複製しました"
      }
    }
  },
  sys_user_permission_set: {
    label: "ユーザー権限セット",
    pluralLabel: "ユーザー権限セット",
    description: "ユーザーへの権限セットの直接割り当て（組織スコープ可能）。",
    fields: {
      id: {
        label: "割り当て ID",
        help: "割り当ての UUID。"
      },
      user_id: {
        label: "ユーザー",
        help: "sys_user への外部キー。"
      },
      permission_set_id: {
        label: "権限セット",
        help: "sys_permission_set への外部キー。"
      },
      organization_id: {
        label: "組織",
        help: "オプションの組織スコープ。NULL = すべての組織コンテキストで適用。"
      },
      granted_by: {
        label: "付与者",
        help: "この権限セットを付与したユーザー。"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      }
    }
  },
  sys_role_permission_set: {
    label: "ロール権限セット",
    pluralLabel: "ロール権限セット",
    description: "権限セットをロールにバインドします。",
    fields: {
      id: {
        label: "バインド ID",
        help: "ロール権限セットバインドの UUID。"
      },
      role_id: {
        label: "ロール",
        help: "sys_role への外部キー。"
      },
      permission_set_id: {
        label: "権限セット",
        help: "sys_permission_set への外部キー。"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      }
    }
  }
};
