#!/usr/bin/env node
// Generates the AI-facing markdown reference from react-blocks.contract.json.
// Run: node skills/objectstack-ui/contracts/build-ref.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const contract = JSON.parse(readFileSync(join(here, 'react-blocks.contract.json'), 'utf8'));
const out = join(here, '..', 'references', 'react-blocks.md');

const esc = (s) => String(s).replace(/\|/g, '\\|');
const KIND_ORDER = { data: 0, controlled: 1, callback: 2, layout: 3 };

const lines = [];
lines.push('---');
lines.push('title: React-tier component contract');
lines.push('description: The props each injected component accepts in kind:\'react\' page source (ADR-0081). GENERATED from contracts/react-blocks.contract.json — do not edit by hand.');
lines.push('---');
lines.push('');
lines.push('{/* GENERATED by contracts/build-ref.mjs from react-blocks.contract.json — do not edit. */}');
lines.push('');
lines.push(`# React-tier component contract (${contract.adr})`);
lines.push('');
lines.push(contract.note);
lines.push('');
lines.push('Prop **kind**: `data` = static/declarative (mirrors the registry inputs) · `controlled` = drive from React state · `callback` = a React function the component calls.');
lines.push('');

for (const b of contract.blocks) {
  lines.push(`## \`<${b.tag}>\` — \`${b.schemaType}\``);
  lines.push('');
  lines.push(b.summary);
  lines.push('');
  lines.push('| prop | type | kind | required | description |');
  lines.push('|------|------|------|:--------:|-------------|');
  const props = [...b.props].sort((a, z) => (KIND_ORDER[a.kind] - KIND_ORDER[z.kind]));
  for (const p of props) {
    lines.push(`| \`${p.name}\` | \`${esc(p.type)}\` | ${p.kind} | ${p.required ? '✓' : ''} | ${esc(p.description)} |`);
  }
  lines.push('');
}

if (contract.alsoAvailable) {
  lines.push('## Also available');
  lines.push('');
  lines.push(contract.alsoAvailable.note);
  lines.push('');
  lines.push('Injected scope (closure variables, reference directly — not props): ' + contract.alsoAvailable.scope.map((s) => `\`${s}\``).join(', ') + '.');
  lines.push('');
}

writeFileSync(out, lines.join('\n'));
console.log('✅ wrote', out, `(${contract.blocks.length} blocks)`);
