// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_webhook: {
    label: "Webhook",
    pluralLabel: "Webhooks",
    description: "Suscripción saliente de Webhook HTTP. Se crea mediante defineWebhook() en código o con el editor de Studio; la ejecuta el plugin del conector HTTP.",
    fields: {
      id: {
        label: "ID de webhook"
      },
      name: {
        label: "Nombre",
        help: "Nombre snake_case único; se usa en los registros y en la auditoría."
      },
      label: {
        label: "Nombre visible"
      },
      object_name: {
        label: "Objeto",
        help: "Nombre corto del objeto cuyos eventos de registro (create/update/delete) activan este Webhook."
      },
      triggers: {
        label: "Desencadenantes",
        help: "Lista de eventos separada por comas: create,update,delete."
      },
      url: {
        label: "URL de destino",
        help: "Endpoint externo que recibe el POST."
      },
      method: {
        label: "Método HTTP",
        help: "GET / POST / PUT / PATCH / DELETE"
      },
      description: {
        label: "Descripción"
      },
      active: {
        label: "Activo",
        help: "Los Webhooks inactivos se omiten en el despachador."
      },
      definition_json: {
        label: "Definición",
        help: "JSON serializado de Webhook (consulte @objectstack/spec/automation/webhook): configuración completa de cabeceras/auth/reintentos/payload."
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      active: {
        label: "Activo"
      },
      inactive: {
        label: "Inactivo"
      },
      by_object: {
        label: "Por objeto"
      },
      all_webhooks: {
        label: "Todos"
      }
    }
  },
  sys_webhook_delivery: {
    label: "Webhook Delivery",
    pluralLabel: "Webhook Deliveries",
    description: "Durable outbox row for one webhook attempt. Managed by @objectstack/plugin-webhooks; do not write directly.",
    fields: {
      id: {
        label: "Delivery ID",
        help: "UUID — also doubles as the receiver-side idempotency key"
      },
      webhook_id: {
        label: "Webhook ID",
        help: "FK to sys_webhook.id (loosely coupled — denormalised URL/secret on row)"
      },
      event_id: {
        label: "Event ID",
        help: "Source event id; UNIQUE(event_id, webhook_id) for dedup"
      },
      event_type: {
        label: "Event Type",
        help: "e.g. data.record.created"
      },
      url: {
        label: "Target URL",
        help: "Snapshotted at enqueue so config edits do not rewrite live rows"
      },
      method: {
        label: "Method"
      },
      headers_json: {
        label: "Headers JSON"
      },
      secret: {
        label: "HMAC Secret"
      },
      timeout_ms: {
        label: "Timeout (ms)"
      },
      payload_json: {
        label: "Payload JSON"
      },
      partition_key: {
        label: "Partition",
        help: "hash(webhook_id) mod partitionCount — precomputed for cheap WHERE"
      },
      status: {
        label: "Status",
        help: "pending | in_flight | success | failed | dead"
      },
      attempts: {
        label: "Attempts",
        help: "Number of POST attempts made so far"
      },
      claimed_by: {
        label: "Claimed By"
      },
      claimed_at: {
        label: "Claimed At (ms)"
      },
      next_retry_at: {
        label: "Next Retry At (ms)"
      },
      last_attempted_at: {
        label: "Last Attempted At (ms)"
      },
      response_code: {
        label: "HTTP Status"
      },
      response_body: {
        label: "Response Body (capped)"
      },
      error: {
        label: "Error"
      },
      created_at: {
        label: "Created At (ms)"
      },
      updated_at: {
        label: "Updated At (ms)"
      }
    },
    _views: {
      recent: {
        label: "Recent"
      },
      failures: {
        label: "Failures"
      },
      in_flight: {
        label: "In Flight"
      },
      pending: {
        label: "Pending"
      },
      by_status: {
        label: "By Status"
      },
      by_webhook: {
        label: "By Webhook"
      },
      all_deliveries: {
        label: "All"
      }
    },
    _actions: {
      redeliver: {
        label: "Redeliver",
        confirmText: "Replay this delivery? The receiver will get the original payload again — they must be idempotent on the X-Objectstack-Delivery header.",
        successMessage: "Queued for redelivery"
      }
    }
  }
};
