/**
 * ObjectUI — codegen the JSX type surface from the registry manifest (ADR-0080 §3)
 *
 * Emits a `.d.ts` that augments `JSX.IntrinsicElements` so a constrained
 * JSX-source page type-checks in `.tsx`: tag name === registry `type` key,
 * attributes === the component's manifest `inputs`. This is a TYPE-CHECKING
 * fiction — no real React intrinsic named `flex` exists; the interpreter
 * fulfills it via the registry at render time.
 */

import type { Manifest, ManifestComponent, ManifestInput } from './types.js';

export interface CodegenOptions {
  /** include a self-contained minimal JSX namespace so the d.ts type-checks
   *  standalone (no React types needed). Default true. */
  standaloneJsx?: boolean;
}

export function generateDts(manifest: Manifest, options: CodegenOptions = {}): string {
  const { standaloneJsx = true } = options;
  const comps = Object.values(manifest.components).sort((a, b) => a.type.localeCompare(b.type));

  const interfaces = comps.map(emitInterface).join('\n\n');
  const intrinsics = comps
    .map((c) => `      ${JSON.stringify(c.type)}: ${propsName(c.type)};`)
    .join('\n');

  const baseElement = standaloneJsx
    ? `
    // minimal, so the surface type-checks without pulling React types
    type Element = unknown;
    interface ElementClass {}
    interface ElementAttributesProperty {}
    interface ElementChildrenAttribute { children: object; }`
    : '';

  return `// AUTO-GENERATED by @object-ui/sdui-parser — DO NOT EDIT.
// Source of truth: ComponentRegistry inputs (ADR-0080 §3). Regenerate via codegen.
/* eslint-disable */

export interface SduiBaseProps {
  id?: string;
  className?: string;
  style?: Record<string, unknown>;
  visible?: boolean;
  visibleOn?: string;
  disabled?: boolean;
  disabledOn?: string;
  children?: unknown;
}

${interfaces}

declare global {
  namespace JSX {
    interface IntrinsicElements {
${intrinsics}
    }${baseElement}
  }
}

export {};
`;
}

function emitInterface(comp: ManifestComponent): string {
  const lines = comp.inputs
    .filter((i) => i.type !== 'slot')
    .map((i) => `  ${propLine(i)}`)
    .join('\n');
  return `export interface ${propsName(comp.type)} extends SduiBaseProps {\n${lines}\n}`;
}

function propLine(input: ManifestInput): string {
  const opt = input.required ? '' : '?';
  return `${quoteKeyIfNeeded(input.name)}${opt}: ${tsType(input)};`;
}

function tsType(input: ManifestInput): string {
  switch (input.type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return 'unknown[]';
    case 'object':
      return 'Record<string, unknown>';
    case 'enum': {
      const vals = (input.enum ?? []).map((e) => (typeof e === 'object' ? e.value : e));
      return vals.length ? vals.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    }
    case 'string':
    case 'color':
    case 'date':
    case 'code':
    case 'file':
    default:
      return 'string';
  }
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const quoteKeyIfNeeded = (name: string): string => (IDENT.test(name) ? name : JSON.stringify(name));

/** 'object-grid' -> 'ObjectGrid', 'record:details' -> 'RecordDetails' */
export function propsName(type: string): string {
  const pascal = type
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
  return `${pascal}Props`;
}

/**
 * Generate the human-facing PUBLIC block list (the curated "清单") from a
 * manifest — a Markdown table. Derived, never hand-maintained (ADR-0046).
 */
export function generateBlockList(manifest: Manifest): string {
  const rows = Object.values(manifest.components)
    .sort((a, b) => a.type.localeCompare(b.type))
    .map((c) => {
      const req = c.inputs.filter((i) => i.required).map((i) => i.name);
      const binds = c.inputs.filter((i) => i.binding).map((i) => `${i.name}:${i.binding}`);
      return `| \`${c.type}\` | ${c.namespace ?? '—'} | ${c.isContainer ? '✓' : ''} | ${req.join(', ') || '—'} | ${binds.join(', ') || '—'} |`;
    });
  return [
    `# SDUI public blocks (${Object.keys(manifest.components).length})`,
    '',
    '> Auto-generated from the registry `tier:\'public\'` set (ADR-0080). Do not edit by hand.',
    '',
    '| block | plugin | container | required props | bindings |',
    '|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}
