// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enObjects: NonNullable<TranslationData['objects']> = {
  sys_approval_request: {
    label: "Approval Request",
    pluralLabel: "Approval Requests",
    description: "Live approval instance tracked per submission",
    fields: {
      id: {
        label: "Request ID"
      },
      organization_id: {
        label: "Organization",
        help: "Tenant that owns this approval request (propagated from submitter context)"
      },
      process_name: {
        label: "Source",
        help: "Origin of the request — `flow:<flowName|nodeId>` for node-driven approvals"
      },
      object_name: {
        label: "Object"
      },
      record_id: {
        label: "Record ID"
      },
      submitter_id: {
        label: "Submitter"
      },
      submitter_comment: {
        label: "Submitter Comment"
      },
      status: {
        label: "Status",
        help: "Lifecycle state of the request",
        options: {
          pending: "pending",
          approved: "approved",
          rejected: "rejected",
          recalled: "recalled"
        }
      },
      current_step: {
        label: "Current Step",
        help: "Machine name of the step awaiting approval"
      },
      current_step_index: {
        label: "Current Step Index"
      },
      pending_approvers: {
        label: "Pending Approvers",
        help: "Comma-separated user ids who can act on the current step"
      },
      payload_json: {
        label: "Snapshot",
        help: "Record snapshot at submission time"
      },
      flow_run_id: {
        label: "Flow Run",
        help: "Suspended automation run id this request gates (ADR-0019). The decision resumes it."
      },
      flow_node_id: {
        label: "Flow Node",
        help: "Approval node id within the flow that opened this request (ADR-0019)."
      },
      node_config_json: {
        label: "Node Config",
        help: "Snapshot of the Approval node config (approvers/behavior) for node-driven requests (ADR-0019)."
      },
      completed_at: {
        label: "Completed At"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      my_pending: {
        label: "My Pending"
      },
      submitted_by_me: {
        label: "I Submitted"
      },
      completed: {
        label: "Completed"
      },
      all_requests: {
        label: "All"
      }
    }
  },
  sys_approval_action: {
    label: "Approval Action",
    pluralLabel: "Approval Actions",
    description: "Append-only audit trail for approval actions",
    fields: {
      id: {
        label: "Action ID"
      },
      organization_id: {
        label: "Organization",
        help: "Tenant that owns this action (mirrors the parent request)"
      },
      request_id: {
        label: "Request"
      },
      step_name: {
        label: "Step",
        help: "Machine name of the step at the time of the action"
      },
      step_index: {
        label: "Step Index"
      },
      action: {
        label: "Action",
        options: {
          submit: "submit",
          approve: "approve",
          reject: "reject",
          recall: "recall",
          escalate: "escalate"
        }
      },
      actor_id: {
        label: "Actor"
      },
      comment: {
        label: "Comment"
      },
      created_at: {
        label: "Created At"
      }
    },
    _views: {
      recent: {
        label: "Recent"
      },
      by_actor: {
        label: "By Actor"
      },
      all_actions: {
        label: "All"
      }
    }
  }
};
