// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_approval_request: {
    label: "Solicitud de aprobación",
    pluralLabel: "Solicitudes de aprobación",
    description: "Instancia activa de aprobación registrada por envío",
    fields: {
      id: {
        label: "ID de solicitud"
      },
      organization_id: {
        label: "Organización",
        help: "Tenant que posee esta solicitud de aprobación (propagado desde el contexto del solicitante)."
      },
      process_name: {
        label: "Origen",
        help: "Origen de la solicitud — `flow:<flowName|nodeId>` para aprobaciones por nodo"
      },
      object_name: {
        label: "Objeto"
      },
      record_id: {
        label: "ID de registro"
      },
      submitter_id: {
        label: "Solicitante"
      },
      submitter_comment: {
        label: "Comentario del solicitante"
      },
      status: {
        label: "Estado",
        help: "Estado del ciclo de vida de la solicitud.",
        options: {
          pending: "Pendiente",
          approved: "Aprobada",
          rejected: "Rechazada",
          recalled: "Retirada"
        }
      },
      current_step: {
        label: "Paso actual",
        help: "Nombre técnico del paso pendiente de aprobación."
      },
      current_step_index: {
        label: "Índice del paso actual"
      },
      pending_approvers: {
        label: "Aprobadores pendientes",
        help: "ID de usuario separados por comas que pueden actuar en el paso actual."
      },
      payload_json: {
        label: "Instantánea",
        help: "Instantánea del registro en el momento del envío."
      },
      flow_run_id: {
        label: "Flow Run",
        help: "Suspended automation run id this request gates (ADR-0019). The decision resumes it."
      },
      flow_node_id: {
        label: "Flow Node",
        help: "Approval node id within the flow that opened this request (ADR-0019)."
      },
      node_config_json: {
        label: "Node Config",
        help: "Snapshot of the Approval node config (approvers/behavior) for node-driven requests (ADR-0019)."
      },
      completed_at: {
        label: "Completado el"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      my_pending: {
        label: "Mis pendientes"
      },
      submitted_by_me: {
        label: "Enviadas por mí"
      },
      completed: {
        label: "Completadas"
      },
      all_requests: {
        label: "Todas"
      }
    }
  },
  sys_approval_action: {
    label: "Acción de aprobación",
    pluralLabel: "Acciones de aprobación",
    description: "Registro de auditoría append-only para acciones de aprobación",
    fields: {
      id: {
        label: "ID de acción"
      },
      organization_id: {
        label: "Organización",
        help: "Tenant que posee esta acción (refleja la solicitud principal)."
      },
      request_id: {
        label: "Solicitud"
      },
      step_name: {
        label: "Paso",
        help: "Nombre técnico del paso en el momento de la acción."
      },
      step_index: {
        label: "Índice del paso"
      },
      action: {
        label: "Acción",
        options: {
          submit: "Enviar",
          approve: "Aprobar",
          reject: "Rechazar",
          recall: "Retirar",
          escalate: "Escalar"
        }
      },
      actor_id: {
        label: "Actor"
      },
      comment: {
        label: "Comentario"
      },
      created_at: {
        label: "Creado el"
      }
    },
    _views: {
      recent: {
        label: "Recientes"
      },
      by_actor: {
        label: "Por actor"
      },
      all_actions: {
        label: "Todas"
      }
    }
  }
};
