// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enMetadataForms: NonNullable<TranslationData['metadataForms']> = {
  object: {
    label: "Object",
    sections: {
      basics: {
        label: "Basics",
        description: "Identity, labels, and taxonomy."
      },
      fields: {
        label: "Fields",
        description: "Define the data model — each row becomes a column in the database table."
      },
      capabilities: {
        label: "Capabilities",
        description: "System features and API exposure."
      },
      advanced: {
        label: "Advanced",
        description: "State machines, actions, and storage."
      }
    },
    fields: {
      name: {
        helpText: "snake_case unique identifier (immutable after creation)"
      },
      label: {
        helpText: "Singular display name (e.g. \"Account\")"
      },
      pluralLabel: {
        helpText: "Plural display name (e.g. \"Accounts\")"
      },
      icon: {
        helpText: "Lucide icon name (e.g. \"building\", \"users\")"
      },
      description: {
        helpText: "Developer documentation"
      },
      tags: {
        helpText: "Categorization tags (e.g. \"sales\", \"system\")"
      },
      active: {
        helpText: "Is the object active and usable"
      },
      isSystem: {
        helpText: "System object (protected from deletion)"
      },
      abstract: {
        helpText: "Abstract base (cannot be instantiated)"
      },
      fields: {
        helpText: "Add the columns this object will store"
      },
      "fields.label": {
        helpText: "Display label"
      },
      "fields.type": {
        helpText: "Field type"
      },
      "fields.description": {
        helpText: "Developer documentation for this column"
      },
      "fields.required": {
        helpText: "Must be set on every record"
      },
      "fields.unique": {
        helpText: "Disallow duplicate values"
      },
      "fields.indexed": {
        helpText: "Create a database index for faster querying"
      },
      "fields.readonly": {
        helpText: "Visible but never user-editable"
      },
      "fields.immutable": {
        helpText: "Editable on create, locked thereafter"
      },
      "fields.hidden": {
        helpText: "Hidden from default UI"
      },
      "fields.searchable": {
        helpText: "Include in full-text search"
      },
      "fields.sortable": {
        helpText: "Allow sorting on this column"
      },
      "fields.filterable": {
        helpText: "Allow filtering on this column"
      },
      "fields.defaultValue": {
        helpText: "Default value for new records (JSON literal)"
      },
      "fields.placeholder": {
        helpText: "Placeholder hint"
      },
      "fields.maxLength": {
        helpText: "Max characters"
      },
      "fields.minLength": {
        helpText: "Min characters"
      },
      "fields.min": {
        helpText: "Minimum value"
      },
      "fields.max": {
        helpText: "Maximum value"
      },
      "fields.precision": {
        helpText: "Total digits"
      },
      "fields.scale": {
        helpText: "Decimal places"
      },
      "fields.options": {
        helpText: "Available choices"
      },
      "fields.options.icon": {
        helpText: "Lucide icon name"
      },
      "fields.reference": {
        helpText: "Target object (for lookup/master_detail)"
      },
      "fields.referenceFilter": {
        helpText: "CEL filter applied to the picker"
      },
      "fields.cascadeDelete": {
        helpText: "Delete children when parent is deleted"
      },
      "fields.multiple": {
        helpText: "Allow selecting multiple records"
      },
      "fields.formula": {
        helpText: "CEL formula expression"
      },
      "fields.returnType": {
        helpText: "Result type for formulas"
      },
      "fields.summaryType": {
        helpText: "Aggregation"
      },
      "fields.summaryField": {
        helpText: "Field on child object to aggregate"
      },
      "fields.displayFormat": {
        helpText: "e.g. \"INV-{0000}\""
      },
      "fields.startingNumber": {
        helpText: "Starting sequence value"
      },
      "fields.language": {
        helpText: "Editor language (e.g. sql, javascript)"
      },
      "fields.validation": {
        helpText: "CEL predicate — must evaluate true"
      },
      "fields.errorMessage": {
        helpText: "Shown when validation fails"
      },
      "fields.audit": {
        helpText: "Audit changes to this field"
      },
      "fields.trackHistory": {
        helpText: "Keep change history"
      },
      "fields.pii": {
        helpText: "Personally identifiable information"
      },
      "fields.encrypted": {
        helpText: "Encrypt at rest"
      },
      capabilities: {
        helpText: "Enable/disable system features"
      },
      datasource: {
        helpText: "Target datasource ID (default: \"default\")"
      }
    }
  },
  field: {
    label: "Field",
    sections: {
      basics: {
        label: "Basics",
        description: "Core field identity and constraints."
      },
      configuration: {
        label: "Configuration",
        description: "Field-type specific settings (visible blocks depend on the chosen type)."
      },
      formula: {
        label: "Formula & Computed",
        description: "Calculated values and roll-up summaries."
      },
      advanced: {
        label: "Advanced",
        description: "Database, UI, audit, and security settings."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case, immutable after creation)"
      },
      label: {
        helpText: "Display name for users"
      },
      type: {
        helpText: "Data type of this field"
      },
      group: {
        helpText: "Group name for form layout"
      },
      description: {
        helpText: "Help text shown to users"
      },
      required: {
        helpText: "User must provide a value"
      },
      unique: {
        helpText: "No two records can have the same value"
      },
      multiple: {
        helpText: "Allow multiple values (for select/lookup)"
      },
      defaultValue: {
        helpText: "Default value for new records"
      },
      minLength: {
        helpText: "Minimum character length"
      },
      maxLength: {
        helpText: "Maximum character length"
      },
      min: {
        helpText: "Minimum value"
      },
      max: {
        helpText: "Maximum value"
      },
      precision: {
        helpText: "Decimal places (e.g., 2 for $10.50)"
      },
      scale: {
        helpText: "Number of decimal digits"
      },
      options: {
        helpText: "Available options (label/value pairs)"
      },
      reference: {
        helpText: "Referenced object name"
      },
      referenceFilters: {
        helpText: "Filter expressions (e.g., \"active = true\")"
      },
      deleteBehavior: {
        helpText: "What happens when referenced record is deleted"
      },
      expression: {
        helpText: "CEL expression to calculate this field (makes it read-only)"
      },
      summaryOperations: {
        helpText: "Roll-up summary configuration (for parent-child relationships)"
      },
      cached: {
        helpText: "Caching configuration for computed fields"
      },
      columnName: {
        helpText: "Physical column name in database (defaults to field name)"
      },
      index: {
        helpText: "Create database index for faster queries"
      },
      externalId: {
        helpText: "Mark as external ID for upsert operations"
      },
      readonly: {
        helpText: "Field is read-only in forms"
      },
      hidden: {
        helpText: "Hide field from default UI views"
      },
      searchable: {
        helpText: "Include in global search results"
      },
      sortable: {
        helpText: "Allow sorting lists by this field"
      },
      auditTrail: {
        helpText: "Track detailed changes with user and timestamp"
      },
      trackFeedHistory: {
        helpText: "Show changes in activity feed"
      },
      encryptionConfig: {
        helpText: "Field-level encryption (GDPR/HIPAA/PCI-DSS)"
      },
      maskingRule: {
        helpText: "Data masking rules for PII protection"
      }
    }
  },
  trigger: {
    label: "Trigger"
  },
  validation: {
    label: "Validation Rule"
  },
  hook: {
    label: "Hook",
    sections: {
      identity: {
        label: "Identity",
        description: "What this hook is and when it fires."
      },
      body: {
        label: "Body",
        description: "Inline expression or sandboxed JavaScript executed when the hook fires."
      },
      legacy_handler: {
        label: "Legacy handler",
        description: "Function name reference — deprecated in favour of body."
      },
      execution: {
        label: "Execution"
      }
    },
    fields: {
      name: {
        helpText: "snake_case identifier (immutable after creation)"
      },
      object: {
        helpText: "Target object name (or \"*\" for global)"
      },
      events: {
        helpText: "Lifecycle events (e.g. beforeInsert, afterUpdate)"
      },
      priority: {
        helpText: "Lower numbers run first"
      },
      body: {
        helpText: "Either an L1 expression or an L2 sandboxed JS body"
      },
      "body.language": {
        helpText: "expression = pure formula; js = sandboxed JavaScript"
      },
      "body.source": {
        helpText: "Function body source — no top-level imports"
      },
      "body.capabilities": {
        helpText: "Allowed ctx APIs (api.read, api.write, crypto.uuid, log, …)"
      },
      "body.timeoutMs": {
        helpText: "Per-invocation timeout (ms)"
      },
      handler: {
        helpText: "Handler function name (deprecated — prefer `body`)"
      },
      async: {
        helpText: "Run in background, do not block the transaction"
      },
      condition: {
        helpText: "Optional formula — skip the hook when this evaluates to false"
      }
    }
  },
  view: {
    label: "View",
    sections: {
      basics: {
        label: "Basics",
        description: "Identity and primary surface."
      },
      columns_filters: {
        label: "Columns & filters",
        description: "What rows show and how users filter them."
      },
      table_options: {
        label: "Table options",
        description: "Grid-only display options."
      },
      kanban: {
        label: "Kanban",
        description: "Kanban-specific board configuration."
      },
      calendar: {
        label: "Calendar",
        description: "Calendar-specific configuration."
      },
      gantt: {
        label: "Gantt",
        description: "Gantt-specific configuration."
      },
      gallery: {
        label: "Gallery",
        description: "Gallery-specific configuration."
      },
      timeline: {
        label: "Timeline",
        description: "Timeline-specific configuration."
      },
      chart: {
        label: "Chart",
        description: "Chart-specific configuration."
      },
      navigation_sharing: {
        label: "Navigation & sharing",
        description: "Where this view appears and who can see it."
      }
    },
    fields: {
      name: {
        helpText: "snake_case, unique per environment"
      },
      type: {
        helpText: "Primary view surface"
      },
      data: {
        helpText: "Data source — e.g. {\"provider\":\"object\",\"object\":\"task\"}"
      },
      columns: {
        helpText: "Columns to display (field names from selected object)"
      },
      filter: {
        helpText: "Filter conditions"
      },
      sort: {
        helpText: "Default sort order"
      },
      searchableFields: {
        helpText: "Field names available for quick search"
      },
      filterableFields: {
        helpText: "Field names available for filtering"
      }
    }
  },
  page: {
    label: "Page",
    sections: {
      basics: {
        label: "Basics",
        description: "Page identity and template."
      },
      data_context: {
        label: "Data Context",
        description: "Record binding and page-local state."
      },
      layout: {
        label: "Layout",
        description: "Page regions and components placed within them."
      },
      advanced: {
        label: "Advanced",
        description: "Activation, audience, and accessibility."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Page title shown to users"
      },
      icon: {
        helpText: "Icon for navigation menu"
      },
      type: {
        helpText: "Page type (record, home, app, dashboard, etc.)"
      },
      template: {
        helpText: "Layout template (e.g., \"header-sidebar-main\")"
      },
      description: {
        helpText: "Page description for navigation"
      },
      object: {
        helpText: "Bound object (for Record pages)"
      },
      variables: {
        helpText: "Local page state variables"
      },
      regions: {
        helpText: "Layout regions (header, main, sidebar, footer) with components"
      },
      isDefault: {
        helpText: "Set as default page for this page type"
      },
      kind: {
        helpText: "Page override mode: full or slotted (for record pages)"
      },
      assignedProfiles: {
        helpText: "Profiles that can access this page"
      },
      aria: {
        helpText: "Accessibility attributes (ARIA labels, roles)"
      }
    }
  },
  dashboard: {
    label: "Dashboard",
    sections: {
      basics: {
        label: "Basics",
        description: "Dashboard identity and description."
      },
      layout: {
        label: "Layout",
        description: "Grid sizing and refresh cadence."
      },
      widgets: {
        label: "Widgets",
        description: "Cards and charts placed on the grid."
      },
      filters: {
        label: "Filters",
        description: "Default and global filters applied across widgets."
      },
      advanced: {
        label: "Advanced",
        description: "Accessibility and performance tuning."
      }
    },
    fields: {
      name: {
        helpText: "snake_case unique identifier"
      },
      label: {
        helpText: "Display name"
      },
      columns: {
        helpText: "Grid columns (default 12)"
      },
      gap: {
        helpText: "Grid gap (Tailwind units)"
      },
      refreshInterval: {
        helpText: "Auto-refresh (seconds)"
      },
      header: {
        helpText: "Dashboard header config (title, subtitle, actions)"
      },
      widgets: {
        helpText: "Dashboard widgets with position and sizing"
      },
      dateRange: {
        helpText: "Default date range selector"
      },
      globalFilters: {
        helpText: "Filters applied to all widgets"
      },
      aria: {
        helpText: "Accessibility labels"
      },
      performance: {
        helpText: "Caching and optimization config"
      }
    }
  },
  app: {
    label: "Application",
    sections: {
      basics: {
        label: "Basics",
        description: "App identity and activation."
      },
      navigation: {
        label: "Navigation",
        description: "Sidebar items and area grouping."
      },
      content: {
        label: "Content",
        description: "Objects and APIs this app uses."
      },
      branding: {
        label: "Branding",
        description: "Theme colors and logo."
      },
      access_and_sharing: {
        label: "Access & sharing",
        description: "Who can access this app and how it can be embedded."
      }
    },
    fields: {
      name: {
        helpText: "snake_case, unique"
      },
      icon: {
        helpText: "Lucide icon name (e.g. \"users\", \"briefcase\")"
      },
      isDefault: {
        helpText: "Make this the default app for new users"
      },
      navigation: {
        helpText: "Nav tree — recursive structure"
      },
      areas: {
        helpText: "Group items into collapsible areas"
      },
      homePageId: {
        helpText: "Landing page when app opens"
      },
      mobileNavigation: {
        helpText: "Bottom tab bar config for mobile"
      },
      objects: {
        helpText: "Object names this app exposes"
      },
      apis: {
        helpText: "API endpoint definitions"
      },
      defaultAgent: {
        helpText: "AI agent for the ambient assistant button"
      },
      branding: {
        helpText: "Primary/secondary colors, logo, theme"
      },
      requiredPermissions: {
        helpText: "Permissions needed to access this app"
      },
      sharing: {
        helpText: "Public/internal/restricted access control"
      },
      embed: {
        helpText: "iFrame embed configuration"
      },
      aria: {
        helpText: "Accessibility labels"
      }
    }
  },
  action: {
    label: "Action",
    sections: {
      basics: {
        label: "Basics",
        description: "Action identity and presentation."
      },
      behavior: {
        label: "Behavior",
        description: "Configure what happens when the action is triggered."
      },
      placement: {
        label: "Placement",
        description: "Where and when the action button appears."
      },
      advanced: {
        label: "Advanced",
        description: "Bulk operations, AI exposure, and API request shape."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Button text shown to users"
      },
      objectName: {
        helpText: "Object this action belongs to (optional)"
      },
      icon: {
        helpText: "Lucide icon name (e.g., \"check\", \"x-circle\")"
      },
      type: {
        helpText: "What happens when clicked"
      },
      variant: {
        helpText: "Button style (primary=blue, danger=red, ghost=transparent)"
      },
      target: {
        helpText: "URL, flow name, or API endpoint to call"
      },
      method: {
        helpText: "HTTP method (GET, POST, PUT, DELETE)"
      },
      body: {
        helpText: "JavaScript code to execute"
      },
      params: {
        helpText: "User input parameters (show form before executing)"
      },
      confirmText: {
        helpText: "Confirmation message (e.g., \"Are you sure?\")"
      },
      successMessage: {
        helpText: "Success message after completion"
      },
      refreshAfter: {
        helpText: "Refresh the list/page after action completes"
      },
      locations: {
        helpText: "Where to show this action (toolbar, row menu, etc.)"
      },
      component: {
        helpText: "How to render (button, icon, menu item)"
      },
      visible: {
        helpText: "CEL expression: show only when condition is true"
      },
      disabled: {
        helpText: "CEL expression: disable when condition is true"
      },
      shortcut: {
        helpText: "Keyboard shortcut (e.g., \"Ctrl+S\", \"Cmd+Enter\")"
      },
      bulkEnabled: {
        helpText: "Allow applying to multiple selected records"
      },
      aiExposed: {
        helpText: "Allow AI agents to call this action"
      },
      recordIdParam: {
        helpText: "Body parameter name for record ID"
      },
      recordIdField: {
        helpText: "Field to use as record ID (default: \"id\")"
      },
      bodyShape: {
        helpText: "Request body structure (flat or nested)"
      }
    }
  },
  report: {
    label: "Report",
    sections: {
      basics: {
        label: "Basics",
        description: "Identity and data source."
      },
      columns: {
        label: "Columns",
        description: "Columns shown in the report output."
      },
      groupings: {
        label: "Groupings",
        description: "How rows (and columns, for matrix reports) are grouped."
      },
      joined_blocks: {
        label: "Joined blocks",
        description: "Additional blocks joined into a single report (joined reports only)."
      },
      filter_and_chart: {
        label: "Filter & chart",
        description: "Report-level filters and chart presentation."
      },
      advanced: {
        label: "Advanced",
        description: "Accessibility and performance tuning."
      }
    },
    fields: {
      name: {
        helpText: "snake_case unique identifier"
      },
      objectName: {
        helpText: "Data source object"
      },
      type: {
        helpText: "Report type: tabular/summary/matrix/joined"
      },
      columns: {
        helpText: "Columns to display in the report"
      },
      groupingsDown: {
        helpText: "Row grouping levels"
      },
      groupingsAcross: {
        helpText: "Column grouping levels (matrix only)"
      },
      blocks: {
        helpText: "Join multiple objects (joined report only)"
      },
      filter: {
        helpText: "Report-level filters"
      },
      chart: {
        helpText: "Chart config (type, legend, colors)"
      },
      aria: {
        helpText: "Accessibility labels"
      },
      performance: {
        helpText: "Caching and optimization"
      }
    }
  },
  flow: {
    label: "Flow",
    sections: {
      basics: {
        label: "Basics",
        description: "Flow identity and how it starts."
      },
      canvas: {
        label: "Canvas",
        description: "Nodes, edges, and flow variables — consider the visual designer for complex flows."
      },
      execution: {
        label: "Execution",
        description: "Deployment status, identity, and error handling."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Display name for users"
      },
      type: {
        helpText: "How the flow starts (autolaunched, record_change, schedule, screen, api)"
      },
      template: {
        helpText: "Is this a reusable subflow (can be called from other flows)"
      },
      description: {
        helpText: "What this flow does"
      },
      nodes: {
        helpText: "⚠️ Consider using Flow Designer visual editor instead of JSON"
      },
      edges: {
        helpText: "Connections between nodes — use Flow Designer for easier editing"
      },
      variables: {
        helpText: "Flow variables (inputs/outputs)"
      },
      status: {
        helpText: "Deployment status: draft → active → obsolete"
      },
      version: {
        helpText: "Version number (auto-incremented)"
      },
      runAs: {
        helpText: "Execute as system (admin) or user (current user permissions)"
      },
      errorHandling: {
        helpText: "What to do when a node fails (fail, retry, continue)"
      }
    }
  },
  job: {
    label: "Background Job"
  },
  datasource: {
    label: "Datasource"
  },
  external_catalog: {
    label: "External Catalog"
  },
  translation: {
    label: "Translation"
  },
  router: {
    label: "Router"
  },
  function: {
    label: "Function"
  },
  service: {
    label: "Service"
  },
  email_template: {
    label: "Email Template",
    sections: {
      identity: {
        label: "Identity",
        description: "Identifier and content type. The id is referenced by sendTemplate({ template: id, ... })."
      },
      subject: {
        label: "Subject",
        description: "Subject line. Supports {{var.path}} interpolation."
      },
      html_body: {
        label: "HTML body",
        description: "Rich HTML body. Most clients strip <head>, so use inline styles."
      },
      plain_text_body: {
        label: "Plain-text body",
        description: "Optional plain-text alternative. When omitted, the service strips tags from the HTML body to derive one. Providing one improves spam scoring."
      },
      variables: {
        label: "Variables",
        description: "Declared variables. Rendered as hints in Studio and validated by sendTemplate() when required."
      },
      delivery_overrides: {
        label: "Delivery overrides",
        description: "Optional per-template overrides for From / Reply-To."
      },
      status: {
        label: "Status"
      }
    },
    fields: {
      name: {
        helpText: "Dotted snake_case (e.g. auth.password_reset, crm.welcome)"
      },
      locale: {
        helpText: "BCP-47 tag — e.g. en-US, zh-CN"
      },
      variables: {
        helpText: "List of variable names referenced in subject/body"
      },
      fromOverride: {
        helpText: "{ \"name\": \"Acme Sales\", \"address\": \"sales@acme.com\" }"
      },
      replyTo: {
        helpText: "Reply-To email address"
      },
      active: {
        helpText: "When unchecked, sendTemplate() returns TEMPLATE_INACTIVE."
      },
      isSystem: {
        helpText: "Built-in template; tenants may override but should not delete."
      }
    }
  },
  permission: {
    label: "Permission Set",
    sections: {
      identity: {
        label: "Identity",
        description: "Permission Sets stack on top of a Profile to grant additional access. Profiles are the base set assigned 1:1 to each user."
      },
      system_permissions: {
        label: "System Permissions",
        description: "High-level capabilities not tied to a specific object — e.g. manage_users, view_audit_logs."
      },
      object_and_field_permissions: {
        label: "Object & Field Permissions",
        description: "Per-object CRUD + per-field FLS. Edit via the matrix editor or paste JSON here."
      },
      tab_and_row_level_security: {
        label: "Tab & Row-Level Security",
        description: "Tab visibility, RLS policies, and custom context variables for predicate evaluation."
      }
    },
    fields: {
      name: {
        helpText: "Machine name (snake_case)"
      },
      label: {
        helpText: "Display label for admins"
      },
      isProfile: {
        helpText: "Profile = base set assigned to users. Permission Set = additive grant."
      },
      systemPermissions: {
        helpText: "List of system capability keys"
      },
      objects: {
        helpText: "{ \"account\": { allowRead: true, allowEdit: true, ... } }"
      },
      fields: {
        helpText: "{ \"account.amount\": { readable: true, editable: false } }"
      },
      tabPermissions: {
        helpText: "{ \"app_crm\": \"visible\", \"app_admin\": \"hidden\" }"
      },
      rowLevelSecurity: {
        helpText: "Array of RLS policies (see rls.zod.ts)"
      },
      contextVariables: {
        helpText: "Custom variables referenced in RLS predicates"
      }
    }
  },
  profile: {
    label: "Profile",
    sections: {
      identity: {
        label: "Identity",
        description: "Permission Sets stack on top of a Profile to grant additional access. Profiles are the base set assigned 1:1 to each user."
      },
      system_permissions: {
        label: "System Permissions",
        description: "High-level capabilities not tied to a specific object — e.g. manage_users, view_audit_logs."
      },
      object_and_field_permissions: {
        label: "Object & Field Permissions",
        description: "Per-object CRUD + per-field FLS. Edit via the matrix editor or paste JSON here."
      },
      tab_and_row_level_security: {
        label: "Tab & Row-Level Security",
        description: "Tab visibility, RLS policies, and custom context variables for predicate evaluation."
      }
    },
    fields: {
      name: {
        helpText: "Machine name (snake_case)"
      },
      label: {
        helpText: "Display label for admins"
      },
      isProfile: {
        helpText: "Profile = base set assigned to users. Permission Set = additive grant."
      },
      systemPermissions: {
        helpText: "List of system capability keys"
      },
      objects: {
        helpText: "{ \"account\": { allowRead: true, allowEdit: true, ... } }"
      },
      fields: {
        helpText: "{ \"account.amount\": { readable: true, editable: false } }"
      },
      tabPermissions: {
        helpText: "{ \"app_crm\": \"visible\", \"app_admin\": \"hidden\" }"
      },
      rowLevelSecurity: {
        helpText: "Array of RLS policies (see rls.zod.ts)"
      },
      contextVariables: {
        helpText: "Custom variables referenced in RLS predicates"
      }
    }
  },
  role: {
    label: "Role",
    sections: {
      role: {
        label: "Role",
        description: "Roles compose a hierarchy used for record sharing (sales VP → sales mgr → sales rep). Permissions themselves live on Permission Sets and Profiles."
      }
    },
    fields: {
      name: {
        helpText: "snake_case"
      },
      parent: {
        helpText: "Parent role machine name (Reports To)"
      }
    }
  },
  agent: {
    label: "AI Agent",
    sections: {
      identity: {
        label: "Identity",
        description: "How users see and reference this agent."
      },
      ai_configuration: {
        label: "AI Configuration",
        description: "Model selection, instructions, planning, and memory."
      },
      capabilities: {
        label: "Capabilities",
        description: "Skills, tools, and knowledge sources the agent can use."
      },
      access: {
        label: "Access & Security",
        description: "Who can use this agent and what safeguards apply."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Display name (e.g., \"Sales Assistant\")"
      },
      role: {
        helpText: "Agent persona (e.g., \"Customer Support Specialist\")"
      },
      avatar: {
        helpText: "Avatar image URL"
      },
      active: {
        helpText: "Enable/disable this agent"
      },
      instructions: {
        helpText: "System prompt — tell the agent how to behave and what it can do"
      },
      model: {
        helpText: "AI model configuration (provider, model name, temperature, etc.)"
      },
      planning: {
        helpText: "Autonomous reasoning configuration (strategy, max iterations, replan)"
      },
      memory: {
        helpText: "Memory management (short-term, long-term, reflection)"
      },
      lifecycle: {
        helpText: "State machine defining conversation flow"
      },
      skills: {
        helpText: "Skill names (Agent→Skill→Tool architecture)"
      },
      tools: {
        helpText: "Direct tool references (legacy mode)"
      },
      knowledge: {
        helpText: "RAG knowledge access configuration"
      },
      visibility: {
        helpText: "Scope: global, organization, or private"
      },
      access: {
        helpText: "User IDs or role names who can chat with this agent"
      },
      permissions: {
        helpText: "Required permissions to use this agent"
      },
      tenantId: {
        helpText: "Restrict to specific organization ID"
      },
      guardrails: {
        helpText: "Safety rules and content policies"
      }
    }
  },
  tool: {
    label: "AI Tool",
    sections: {
      basics: {
        label: "Basics",
        description: "Tool identity and AI-facing description."
      },
      schemas: {
        label: "Schemas",
        description: "Inputs the tool accepts and the shape of its output."
      },
      access_and_safety: {
        label: "Access & safety",
        description: "Permissions and confirmation requirements."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Display name for Studio UI"
      },
      description: {
        helpText: "Tell AI when to use this tool — be specific!"
      },
      category: {
        helpText: "Tool category (data, action, flow, integration, etc.)"
      },
      objectName: {
        helpText: "Related object (if this tool operates on a specific object)"
      },
      active: {
        helpText: "Enable/disable this tool"
      },
      builtIn: {
        helpText: "Platform built-in tool (vs user-defined)"
      },
      parameters: {
        helpText: "Input parameters — define properties like: {name: {type: \"string\", description: \"...\"}}"
      },
      outputSchema: {
        helpText: "Output schema for validation (optional)"
      },
      requiresConfirmation: {
        helpText: "Ask user to approve before executing (for destructive actions)"
      },
      permissions: {
        helpText: "Required permissions to use this tool"
      }
    }
  },
  skill: {
    label: "AI Skill",
    sections: {
      basics: {
        label: "Basics",
        description: "Skill identity and human-readable description."
      },
      ai_instructions: {
        label: "AI Instructions",
        description: "How the agent should reason with this skill."
      },
      triggers: {
        label: "Triggers",
        description: "When this skill should activate."
      },
      access: {
        label: "Access",
        description: "Required permissions to use this skill."
      }
    },
    fields: {
      name: {
        helpText: "Unique identifier (snake_case)"
      },
      label: {
        helpText: "Display name (e.g., \"Case Management\")"
      },
      description: {
        helpText: "What this skill does"
      },
      active: {
        helpText: "Enable/disable this skill"
      },
      instructions: {
        helpText: "Instructions for AI — tell it how to use these tools together"
      },
      tools: {
        helpText: "Tool names (supports wildcard: action_*)"
      },
      triggerPhrases: {
        helpText: "Natural language phrases that activate this skill"
      },
      triggerConditions: {
        helpText: "Programmatic conditions (e.g., objectName == \"case\")"
      },
      permissions: {
        helpText: "Required permissions to use this skill"
      }
    }
  }
};
