// Vercel Serverless Function — Catch-all API route.
//
// This file MUST be committed to the repository so Vercel can detect it
// as a serverless function during the pre-build phase.
//
// It delegates to the esbuild bundle (`_handler.js`) generated by
// `scripts/bundle-api.mjs` during the Vercel build step.

export { default, config } from './_handler.js';
